name: disco-diffusion-setup
channels:
  - pytorch3d
  - pytorch
  - iopath
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=1_gnu
  - alsa-lib=1.2.3=h516909a_0
  - anyio=3.5.0=py39h06a4308_0
  - asttokens=2.0.5=pyhd3eb1b0_0
  - attrs=21.4.0=pyhd3eb1b0_0
  - babel=2.9.1=pyhd3eb1b0_0
  - backcall=0.2.0=pyhd3eb1b0_0
  - blas=1.0=mkl
  - bleach=4.1.0=pyhd3eb1b0_0
  - brotlipy=0.7.0=py39h27cfd23_1003
  - bzip2=1.0.8=h7f98852_4
  - c-ares=1.18.1=h7f98852_0
  - ca-certificates=2022.2.1=h06a4308_0
  - cairo=1.16.0=ha12eb4b_1010
  - certifi=2021.10.8=py39h06a4308_2
  - cffi=1.15.0=py39hd667e15_1
  - colorama=0.4.4=pyh9f0ad1d_0
  - cryptography=36.0.0=py39h9ce1e76_0
  - cudatoolkit=11.3.1=h2bc3f7f_2
  - dbus=1.13.18=hb2f20db_0
  - debugpy=1.5.1=py39h295c915_0
  - decorator=5.1.1=pyhd3eb1b0_0
  - defusedxml=0.7.1=pyhd3eb1b0_0
  - executing=0.8.3=pyhd3eb1b0_0
  - expat=2.4.7=h27087fc_0
  - ffmpeg=4.3.2=h37c90e5_3
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=hab24e00_0
  - fontconfig=2.13.96=h8e229c2_2
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=0
  - freeglut=3.2.2=h9c3ff4c_1
  - freetype=2.11.0=h70c0345_0
  - fribidi=1.0.10=h36c2ea0_0
  - fvcore=0.1.5.post20220305=pyhd8ed1ab_0
  - gettext=0.21.0=hf68c758_0
  - giflib=5.2.1=h36c2ea0_2
  - glib=2.70.2=h780b84a_4
  - glib-tools=2.70.2=h780b84a_4
  - gmp=6.2.1=h58526e2_0
  - gnutls=3.6.15=he1e5248_0
  - graphite2=1.3.14=h23475e2_0
  - gst-plugins-base=1.18.5=hf529b03_3
  - gstreamer=1.18.5=h9f60fe5_3
  - harfbuzz=4.0.1=h40b6f09_0
  - hdf5=1.12.1=nompi_h2386368_104
  - icu=69.1=h9c3ff4c_0
  - idna=3.3=pyhd3eb1b0_0
  - importlib_metadata=4.8.2=hd3eb1b0_0
  - intel-openmp=2022.0.1=h06a4308_3633
  - iopath=0.1.9=py39
  - ipython=8.1.1=py39h06a4308_0
  - ipython_genutils=0.2.0=pyhd3eb1b0_1
  - jasper=2.0.33=ha77e612_0
  - jbig=2.1=h7f98852_2003
  - jedi=0.18.1=py39h06a4308_1
  - jinja2=3.0.3=pyhd3eb1b0_0
  - jpeg=9e=h7f98852_0
  - json5=0.9.6=pyhd3eb1b0_0
  - jupyter_client=7.1.2=pyhd3eb1b0_0
  - jupyter_core=4.9.2=py39h06a4308_0
  - jupyter_server=1.13.5=pyhd3eb1b0_0
  - jupyterlab=3.3.2=pyhd3eb1b0_0
  - jupyterlab_pygments=0.1.2=py_0
  - jupyterlab_server=2.10.3=pyhd3eb1b0_1
  - keyutils=1.6.1=h166bdaf_0
  - krb5=1.19.3=h3790be6_0
  - lame=3.100=h7f98852_1001
  - lcms2=2.12=hddcbb42_0
  - ld_impl_linux-64=2.36.1=hea4e1c9_2
  - lerc=3.0=h9c3ff4c_0
  - libblas=3.9.0=13_linux64_mkl
  - libcblas=3.9.0=13_linux64_mkl
  - libclang=13.0.1=default_hc23dcda_0
  - libcurl=7.82.0=h7bff187_0
  - libdeflate=1.10=h7f98852_0
  - libedit=3.1.20210910=h7f8727e_0
  - libev=4.33=h516909a_1
  - libevent=2.1.10=h9b69904_4
  - libffi=3.4.2=h7f98852_5
  - libgcc-ng=11.2.0=h1d223b6_14
  - libgfortran-ng=11.2.0=h69a702a_14
  - libgfortran5=11.2.0=h5c6108e_14
  - libglib=2.70.2=h174f98d_4
  - libglu=9.0.0=he1b5a44_1001
  - libgomp=11.2.0=h1d223b6_14
  - libiconv=1.16=h516909a_0
  - libidn2=2.3.2=h7f98852_0
  - libimagequant=2.17.0=h7f98852_1
  - liblapack=3.9.0=13_linux64_mkl
  - liblapacke=3.9.0=13_linux64_mkl
  - libllvm13=13.0.1=hf817b99_2
  - libnghttp2=1.47.0=h727a467_0
  - libogg=1.3.5=h27cfd23_1
  - libopenblas=0.3.18=pthreads_h8fe5266_0
  - libopencv=4.5.5=py39hfb30bf4_6
  - libopus=1.3.1=h7f98852_1
  - libpng=1.6.37=h21135ba_2
  - libpq=14.2=hd57d9b9_0
  - libprotobuf=3.19.4=h780b84a_0
  - libsodium=1.0.18=h7b6447c_0
  - libssh2=1.10.0=ha56f1ee_2
  - libstdcxx-ng=11.2.0=he4da1e4_14
  - libtasn1=4.18.0=h7f98852_0
  - libtiff=4.3.0=h542a066_3
  - libunistring=0.9.10=h7f98852_0
  - libuuid=2.32.1=h7f98852_1000
  - libuv=1.43.0=h7f98852_0
  - libvorbis=1.3.7=h9c3ff4c_0
  - libwebp=1.2.2=h3452ae3_0
  - libwebp-base=1.2.2=h7f98852_1
  - libxcb=1.13=h7f98852_1004
  - libxkbcommon=1.0.3=he3ba5ed_0
  - libxml2=2.9.12=h885dcf4_1
  - libzlib=1.2.11=h36c2ea0_1013
  - lz4-c=1.9.3=h9c3ff4c_1
  - mistune=0.8.4=py39h27cfd23_1000
  - mkl=2022.0.1=h06a4308_117
  - mysql-common=8.0.28=ha770c72_0
  - mysql-libs=8.0.28=hfa10184_0
  - nbclassic=0.3.5=pyhd3eb1b0_0
  - ncurses=6.3=h7f8727e_2
  - nettle=3.7.3=hbbd107a_1
  - nspr=4.33=h295c915_0
  - nss=3.74=hb5efdd6_0
  - numpy=1.22.3=py39h18676bf_0
  - opencv=4.5.5=py39hf3d152e_6
  - openh264=2.1.1=h780b84a_0
  - openjpeg=2.4.0=hb52868f_1
  - openssl=1.1.1n=h7f8727e_0
  - packaging=21.3=pyhd3eb1b0_0
  - pandocfilters=1.5.0=pyhd3eb1b0_0
  - parso=0.8.3=pyhd3eb1b0_0
  - pcre=8.45=h9c3ff4c_0
  - pexpect=4.8.0=pyhd3eb1b0_3
  - pickleshare=0.7.5=pyhd3eb1b0_1003
  - pillow=9.0.1=py39he69867a_1
  - pip=21.2.4=py39h06a4308_0
  - pixman=0.40.0=h36c2ea0_0
  - portalocker=2.4.0=py39hf3d152e_0
  - prometheus_client=0.13.1=pyhd3eb1b0_0
  - pthread-stubs=0.4=h36c2ea0_1001
  - ptyprocess=0.7.0=pyhd3eb1b0_2
  - pure_eval=0.2.2=pyhd3eb1b0_0
  - py-opencv=4.5.5=py39hef51801_6
  - pycparser=2.21=pyhd3eb1b0_0
  - pygments=2.11.2=pyhd3eb1b0_0
  - pyopenssl=22.0.0=pyhd3eb1b0_0
  - pysocks=1.7.1=py39h06a4308_0
  - python=3.9.7=hb7a2778_3_cpython
  - python-dateutil=2.8.2=pyhd3eb1b0_0
  - python_abi=3.9=2_cp39
  - pytorch=1.10.0=py3.9_cuda11.3_cudnn8.2.0_0
  - pytorch-mutex=1.0=cuda
  - pytorch3d=0.6.1=py39_cu113_pyt1100
  - pyyaml=6.0=py39h3811e60_3
  - pyzmq=22.3.0=py39h295c915_2
  - qt=5.12.9=ha98a1a1_5
  - readline=8.1.2=h7f8727e_1
  - requests=2.27.1=pyhd3eb1b0_0
  - send2trash=1.8.0=pyhd3eb1b0_1
  - six=1.16.0=pyhd3eb1b0_1
  - sniffio=1.2.0=py39h06a4308_1
  - sqlite=3.38.0=hc218d9a_0
  - stack_data=0.2.0=pyhd3eb1b0_0
  - tabulate=0.8.9=pyhd8ed1ab_0
  - termcolor=1.1.0=py_2
  - tk=8.6.11=h1ccaba5_0
  - torchaudio=0.10.0=py39_cu113
  - torchvision=0.11.1=py39_cu113
  - tornado=6.1=py39h27cfd23_0
  - tqdm=4.63.0=pyhd8ed1ab_0
  - traitlets=5.1.1=pyhd3eb1b0_0
  - typing_extensions=4.1.1=pyha770c72_0
  - tzdata=2021e=hda174b7_0
  - wcwidth=0.2.5=pyhd3eb1b0_0
  - websocket-client=0.58.0=py39h06a4308_4
  - wheel=0.37.1=pyhd3eb1b0_0
  - x264=1!161.3030=h7f98852_1
  - xorg-fixesproto=5.0=h7f98852_1002
  - xorg-inputproto=2.3.2=h7f98852_1002
  - xorg-kbproto=1.0.7=h7f98852_1002
  - xorg-libice=1.0.10=h7f98852_0
  - xorg-libsm=1.2.3=hd9c2040_1000
  - xorg-libx11=1.7.2=h7f98852_0
  - xorg-libxau=1.0.9=h7f98852_0
  - xorg-libxdmcp=1.1.3=h7f98852_0
  - xorg-libxext=1.3.4=h7f98852_1
  - xorg-libxfixes=5.0.3=h7f98852_1004
  - xorg-libxi=1.7.10=h7f98852_0
  - xorg-libxrender=0.9.10=h7f98852_1003
  - xorg-renderproto=0.11.1=h7f98852_1002
  - xorg-xextproto=7.3.0=h7f98852_1002
  - xorg-xproto=7.0.31=h7f98852_1007
  - xz=5.2.5=h7b6447c_0
  - yacs=0.1.8=pyhd8ed1ab_0
  - yaml=0.2.5=h7f98852_2
  - zeromq=4.3.4=h2531618_0
  - zipp=3.7.0=pyhd3eb1b0_0
  - zlib=1.2.11=h36c2ea0_1013
  - zstd=1.5.2=ha95c52a_0
  - pip:
    - absl-py==1.0.0
    - aiohttp==3.8.1
    - aiosignal==1.2.0
    - antlr4-python3-runtime==4.8
    - argon2-cffi==21.3.0
    - argon2-cffi-bindings==21.2.0
    - async-timeout==4.0.2
    - beautifulsoup4==4.10.0
    - cachetools==5.0.0
    - charset-normalizer==2.0.12
    - click==8.0.4
    - cycler==0.11.0
    - datetime==4.4
    - docker-pycreds==0.4.0
    - einops==0.4.1
    - entrypoints==0.4
    - fonttools==4.31.1
    - frozenlist==1.3.0
    - fsspec==2022.2.0
    - ftfy==6.1.1
    - future==0.18.2
    - gitdb==4.0.9
    - gitpython==3.1.27
    - google-auth==2.6.2
    - google-auth-oauthlib==0.4.6
    - grpcio==1.44.0
    - importlib-metadata==4.11.3
    - ipykernel==6.9.2
    - ipywidgets==7.7.0
    - jsonschema==4.4.0
    - jupyterlab-widgets==1.1.0
    - kiwisolver==1.4.0
    - lpips==0.1.4
    - markdown==3.3.6
    - markupsafe==2.1.1
    - matplotlib==3.5.1
    - matplotlib-inline==0.1.3
    - multidict==6.0.2
    - nbclient==0.5.13
    - nbconvert==6.4.4
    - nbformat==5.2.0
    - nest-asyncio==1.5.4
    - notebook==6.4.10
    - oauthlib==3.2.0
    - omegaconf==2.1.1
    - pandas==1.4.1
    - pathtools==0.1.2
    - promise==2.3
    - prompt-toolkit==3.0.28
    - protobuf==3.19.4
    - psutil==5.9.0
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - pydeprecate==0.3.1
    - pyparsing==3.0.7
    - pyrsistent==0.18.1
    - pytorch-lightning==1.5.10
    - pytz==2022.1
    - requests-oauthlib==1.3.1
    - rsa==4.8
    - scipy==1.8.0
    - sentry-sdk==1.5.8
    - setproctitle==1.2.2
    - setuptools==59.5.0
    - shortuuid==1.0.8
    - smmap==5.0.0
    - soupsieve==2.3.1
    - tensorboard==2.8.0
    - tensorboard-data-server==0.6.1
    - tensorboard-plugin-wit==1.8.1
    - terminado==0.13.3
    - testpath==0.6.0
    - timm==0.5.4
    - torch-fidelity==0.3.0
    - torchmetrics==0.7.2
    - urllib3==1.26.9
    - wandb==0.12.11
    - webencodings==0.5.1
    - werkzeug==2.0.3
    - widgetsnbextension==3.6.0
    - yarl==1.7.2
    - yaspin==2.1.0
    - zope-interface==5.4.0
    - -e git+https://github.com/CompVis/taming-transformers.git
    - -e git+https://github.com/openai/CLIP.git
    - -e git+https://github.com/crowsonkb/guided-diffusion.git
    - -e git+https://github.com/ahupp/ResizeRight.git@packagify
    - -e git+https://github.com/ahupp/MiDaS.git@packagify
    - -e dep/local/
prefix: /home/adam/anaconda3/envs/disco-diffusion-setup
